# Generated by Django 4.0.1 on 2022-02-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admindetails',
            name='password',
            field=models.CharField(default='admin1234', max_length=20),
        ),
        migrations.AlterField(
            model_name='admindetails',
            name='username',
            field=models.CharField(default='admin', max_length=30),
        ),
    ]
