# Generated by Django 4.0.1 on 2022-03-01 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_alter_admindetails_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('qualification', models.CharField(max_length=30)),
                ('experience', models.CharField(max_length=30)),
                ('image', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='admindetails',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='admindetails',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
