# Generated by Django 4.0.1 on 2022-02-28 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('gender', models.BooleanField(default=True)),
                ('address', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=30)),
                ('mobile', models.IntegerField()),
            ],
        ),
    ]
