# Generated by Django 4.0.1 on 2022-03-02 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_booking_contact_login_alter_signup_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
        migrations.AddField(
            model_name='signup',
            name='password',
            field=models.CharField(default=111111, max_length=30),
        ),
    ]
