# Generated by Django 4.0.1 on 2022-03-03 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_delete_login_signup_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='mobile',
            field=models.BigIntegerField(),
        ),
    ]
