# Generated by Django 4.0.1 on 2022-03-03 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_alter_booking_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='gender',
            field=models.BooleanField(default=True),
        ),
    ]
