# Generated by Django 4.0.1 on 2022-03-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_alter_booking_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='gender',
            field=models.CharField(max_length=20),
        ),
    ]
